### ISSUE TITLE
please share screen of admin template 

### ISSUE THREAD

**Issue by Fivell** [formaweb/formadmin#1]
would be great to see how it looks without installing it.

**Comment by brunocascio** [comment]
+1

**Comment by brunocascio** [comment]
![screenshot at 2016-11-20 22 02 56](https://cloud.githubusercontent.com/assets/2397875/20467797/7a0dc5d0-af6d-11e6-8e0f-2a69641f0c05.png)
![screenshot at 2016-11-20 22 03 40](https://cloud.githubusercontent.com/assets/2397875/20467796/7a0d0000-af6d-11e6-97b9-cf966c798c92.png)
![screenshot at 2016-11-20 22 04 06](https://cloud.githubusercontent.com/assets/2397875/20467798/7a2a1820-af6d-11e6-8bea-5dde0c433bef.png)
![screenshot at 2016-11-20 22 04 47](https://cloud.githubusercontent.com/assets/2397875/20467799/7a2bd7f0-af6d-11e6-8ab1-51de0c11d68e.png)
![screenshot at 2016-11-20 22 05 28](https://cloud.githubusercontent.com/assets/2397875/20467800/7a2df67a-af6d-11e6-8bd8-13f55c3e75a6.png)

**Comment by iamajvillalobos** [comment]
Created a PR for this issue at https://github.com/formaweb/formadmin/pull/2
