### ISSUE TITLE
Font-size configurable?

### ISSUE THREAD

**Issue by julien51** [formaweb/formadmin#13]
We found that the default of 16px is pretty high and makes it hard to show a lot of columns on the index page.
Is there a chance you'd be interested in having configurable font-size?
Thanks

**Comment by caiotarifa** [comment]
Hi, @julien51.

Initially, the $font-size is 16px for [better adaptability in the responsive and in the form fields](https://stackoverflow.com/q/2989263/977687). But I think it can be configurable, so I will plan this feature for the next version.

**Comment by caiotarifa** [comment]
Fixed.

**Comment by julien51** [comment]
w00t! Thanks a lot!
