### ISSUE TITLE
Index footer problem

### ISSUE THREAD

**Issue by lsarni** [formaweb/formadmin#16]
On formadmin (0.2.0) the index footer looks like this when there are more than one page:

![image](https://user-images.githubusercontent.com/15196342/31180763-d69ba4e8-a8f5-11e7-88b5-80aef662f8e2.png)

It's fine when there is only one page:

![image](https://user-images.githubusercontent.com/15196342/31180840-0dd4a478-a8f6-11e7-9755-3f8a371994b6.png)

**Comment by caiotarifa** [comment]
Fixed.
