### ISSUE TITLE
Long one word title breaks responsive header

### ISSUE THREAD

**Issue by lsarni** [formaweb/formadmin#17]
If the page title one long word (in my case it was the user email) then this happens on mobile:

![image](https://user-images.githubusercontent.com/15196342/31187641-dd9413d0-a908-11e7-961f-d516420f07be.png)
![image](https://user-images.githubusercontent.com/15196342/31187521-94409f78-a908-11e7-8bbf-430e32a8ba5e.png)

The header and the title bar no longer fit in the screen, the rest of the content does.

If it's more than one word it works great:
![image](https://user-images.githubusercontent.com/15196342/31187606-c8cc0d22-a908-11e7-8725-dacf2cb38e2f.png)

**Comment by caiotarifa** [comment]
Fixed.
