### ISSUE TITLE
Long header on desktop mode

### ISSUE THREAD

**Issue by lautarocastillo** [formaweb/formadmin#24]
Hi guys! I'm trying formadmin and I discovered that the header breaks on desktop when you have many models.
![screenshot from 2018-11-08 08-35-37](https://user-images.githubusercontent.com/18515893/48194408-0ff02100-e334-11e8-83ac-6cbf1743490c.png)

So, is missing the last part of the header. The logout option and the user currently logged.
![screenshot from 2018-11-08 08-39-45](https://user-images.githubusercontent.com/18515893/48193613-036ac900-e332-11e8-8da3-294ece504cd9.png)

On mobile seems perfect!
Many thanks! 
And GREAT JOB by the way!i

**Comment by caiotarifa** [comment]
Hi, @lautarocastillo. Thank you!

Unfortunately there is no way to handle with this without writing some JavaScript

Eventually you can use a [drop down menu](https://activeadmin.info/2-resource-customization.html#customize-the-menu) to minimize impacts.

**Comment by lautarocastillo** [comment]
SOLVED!!
Drop down menu seems perfect!!
Muito obrigado Caio!
