### ISSUE TITLE
Configuration file.

### ISSUE THREAD

**Issue by mabdelfattah** [formaweb/formadmin#3]
Like basic 3-4 colors?

**Comment by caiotarifa** [comment]
[There is a configuration file](https://github.com/formaweb/formadmin/blob/master/app/assets/stylesheets/formadmin/core/_settings.scss) where you can change some settings, not just colors.

I agree that it is still confusing and it would need to be in a separate layer. I will work on that in the next update. :)

**Comment by caiotarifa** [comment]
Solved #11.
