### ISSUE TITLE
Responsive elements not fitting window

### ISSUE THREAD

**Issue by abrambailey** [formaweb/formadmin#5]
![image](https://cloud.githubusercontent.com/assets/978462/23757701/364a10ac-04ad-11e7-8ba8-40b12d75d085.png)

**Comment by caiotarifa** [comment]
Hi, @abrambailey.

It looks like there is a problem setting up the theme within your app.

Make sure you have **removed** the original files in the `assets/stylesheets/active_admin.scss` file.

```
@import 'active_admin/mixins';
@import 'active_admin/base';
```

And **inserted only** the Formadmin file...

```
@import 'formadmin/formadmin';
```

**Comment by abrambailey** [comment]
Congratulations on making a beautiful and functional theme for active admin. This is by far the best I have seen.
